import { useState, type FormEvent, type ReactNode } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import {
  ArrowRight, Award, Building2, Check, ChevronDown, ChevronRight, Cog, Facebook, Globe2,
  HardHat, Instagram, Linkedin, Mail, MapPin, Menu, Music2, Phone, Play, Send, ShoppingCart,
  ShieldCheck, Sparkles, X, Zap, BriefcaseBusiness, Wrench
} from "lucide-react";

const images = [
  { src: "/assets/images/Hero.jpg", label: "Building a stronger tomorrow" },
  { src: "/assets/images/project1.jpeg", label: "Infrastructure & civil works" },
  { src: "/assets/images/project2.jpeg", label: "Site execution" },
  { src: "/assets/images/project3.jpeg", label: "On-site expertise" },
  { src: "/assets/images/project4.jpeg", label: "Project delivery" },
  { src: "/assets/images/project5.jpeg", label: "Engineering solutions" },
  { src: "/assets/images/project6.jpeg", label: "Quality in progress" },
  { src: "/assets/images/project7.jpeg", label: "Built for purpose" },
  { src: "/assets/images/project8.jpeg", label: "Reliable results" },
  { src: "/assets/images/project9.jpeg", label: "Finished project" },
  { src: "/assets/images/project10.jpeg", label: "Commercial delivery" },
  { src: "/assets/images/project11.jpeg", label: "Technical capability" },
];

const services = [
  { icon: HardHat, name: "Civil Engineering", short: "Roads, buildings, drainage and infrastructure that stand the test of time.", bullets: ["Road construction & rehabilitation", "Building and bridge construction", "Drainage, culverts & earthworks", "Foundations, irrigation & land reclamation", "Civil consultancy & project supervision"] },
  { icon: Zap, name: "Electrical Engineering", short: "Safe, dependable power systems for homes, facilities and industry.", bullets: ["Electrical installations", "Power distribution & transformers", "Generators and street lighting", "Testing, commissioning & switchgear", "Preventive maintenance & consultancy"] },
  { icon: Cog, name: "Mechanical Engineering", short: "Precision installation, fabrication and maintenance for critical equipment.", bullets: ["Plant and equipment installation", "Fabrication and generator maintenance", "Pumps, HVAC & refrigeration", "Industrial machinery servicing", "Technical support & consultancy"] },
  { icon: ShoppingCart, name: "Procurement & Supply", short: "The materials, equipment and consumables your project needs, sourced right.", bullets: ["Cables, switches & circuit breakers", "Transformers and generators", "Lighting and electrical fittings", "Mechanical equipment", "Engineering consumables"] },
  { icon: Globe2, name: "Import & Export", short: "Connected logistics and product sourcing for projects across Nigeria.", bullets: ["Engineering materials importation", "Product sourcing & warehousing", "Distribution and logistics support", "Clearing & forwarding", "Export services"] },
  { icon: BriefcaseBusiness, name: "General Contracting", short: "One accountable partner from project scope to successful handover.", bullets: ["Engineering projects", "Equipment supply & procurement", "Facility maintenance", "Government contracts", "Corporate & private developments"] },
];

const videos = [
  ["TdjIs0jwcFg", "Finished project of Nales Global"], ["OHaGZ2MCQ2I", "Nales Global project"], ["T-wDuEzneBQ", "Finished project showcase"],
  ["DPHNRIWdyII", "Men at work"], ["MhCY10qlwM", "On-site execution"], ["PmW56Obgi4M", "Project delivery"], ["FrzARaXDpCg", "Project 06"]
];

function Header() {
  const [open, setOpen] = useState(false);
  const [location] = useLocation();
  const nav = [["/", "Home"], ["/about", "About"], ["/services", "Services"], ["/gallery", "Projects"], ["/contact", "Contact"]];
  return <>
    <header className="site-header">
      <div className="container nav-inner">
        <Link href="/" className="brand" onClick={() => setOpen(false)}><img src="/assets/images/logo.png" alt="Nales Global Services Limited" /><span><b>NALES GLOBAL</b><small>Services Limited</small></span></Link>
        <nav className={open ? "nav-links open" : "nav-links"}>{nav.map(([href, label]) => <Link key={href} href={href} className={location === href ? "active" : ""} onClick={() => setOpen(false)}>{label}</Link>)}<a className="nav-phone" href="tel:+2348030615862"><Phone size={15} /> <span>+234 803 061 5862</span></a><Link href="/contact" className="button button-small" onClick={() => setOpen(false)}>Get a quote <ArrowRight size={15} /></Link></nav>
        <button className="menu-button" aria-label="Toggle menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button>
      </div>
    </header>
  </>;
}

const socialLinks = [
  { label: "TikTok", href: "https://www.tiktok.com/@nalesglobal66?_r=1&_t=ZS-98bG6Ev6UUh", icon: Music2 },
  { label: "Facebook", href: "https://web.facebook.com/profile.php?id=61576814717077", icon: Facebook },
  { label: "Instagram", href: "https://www.instagram.com/nales_global?igsh=ZGNpc3BxOWN2cTdm", icon: Instagram },
  { label: "LinkedIn", href: "https://www.linkedin.com/in/ayodele-awe-5b6a79177/", icon: Linkedin },
];

function SocialLinks({ compact = false }: { compact?: boolean }) { return <div className={compact ? "social-links compact" : "social-links"}>{socialLinks.map(({ label, href, icon: Icon }) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={`Nales Global on ${label}`} title={label}><Icon size={compact ? 16 : 17} /></a>)}</div> }

function Footer() { return <footer><div className="container footer-grid"><div><Link href="/" className="brand footer-brand"><img src="/assets/images/logo.png" alt="Nales Global Services Limited" /><span><b>NALES GLOBAL</b><small>Services Limited</small></span></Link><p className="footer-copy">Engineering capability with a commitment to quality, safety and lasting value.</p><SocialLinks /></div><div><h4>Explore</h4><Link href="/about">About us</Link><Link href="/services">Our services</Link><Link href="/gallery">Project gallery</Link><Link href="/contact">Contact</Link></div><div><h4>Contact</h4><a href="tel:+2348030615862"><Phone size={14} /> +234 803 061 5862</a><a href="mailto:nalesglobal@yahoo.com"><Mail size={14} /> nalesglobal@yahoo.com</a><span><MapPin size={14} /> 10, Ayanbadejo Street<br />Ikosi Ketu, Lagos</span></div></div><div className="container footer-bottom"><span>© 2026 Nales Global Services Limited</span><span>RC 923859 · We deliver value, you grow with us.</span></div></footer> }
function PageHero({ eyebrow, title, text }: { eyebrow: string; title: ReactNode; text: string }) { return <section className="page-hero"><div className="container"><span className="eyebrow light">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div></section> }
function SectionIntro({ eyebrow, title, text, align = "left" }: { eyebrow: string; title: ReactNode; text: string; align?: string }) { return <div className={`section-intro ${align}`}><span className="eyebrow">{eyebrow}</span><h2>{title}</h2><p>{text}</p></div> }
function ServiceCard({ item, detailed = false }: { item: typeof services[number]; detailed?: boolean }) { const Icon = item.icon; return <article className="service-card"><div className="icon-box"><Icon size={25} strokeWidth={1.7} /></div><h3>{item.name}</h3><p>{item.short}</p>{detailed && <ul>{item.bullets.map(b => <li key={b}><Check size={15} />{b}</li>)}</ul>} {!detailed && <Link href="/services" className="text-link">Explore service <ArrowRight size={15} /></Link>}</article> }
function CTA() { return <section className="cta-band"><div className="container cta-inner"><div><span className="eyebrow light">Start a conversation</span><h2>Have a project in mind?</h2><p>Tell us what you’re building. Our team is ready to bring the right expertise to the table.</p></div><div className="cta-actions"><a className="button button-white" href="tel:+2348030615862"><Phone size={16} /> Call our team</a><Link className="button button-outline-white" href="/contact">Send an enquiry <ArrowRight size={16} /></Link></div></div></section> }

function Home() { return <><main>
  <section className="hero"><img className="hero-image" src={images[0].src} alt="Nales Global construction project" /><div className="hero-overlay" /><div className="container hero-content"><div className="hero-copy"><span className="eyebrow light">Nigerian EPC company · RC 923859</span><h1>Infrastructure<br /><em>that moves</em> Nigeria forward.</h1><p>Engineering, procurement and construction expertise for ambitious projects across Nigeria.</p><div className="hero-actions"><Link href="/contact" className="button button-white">Discuss your project <ArrowRight size={17} /></Link><Link href="/gallery" className="button button-ghost">View our work <ChevronRight size={17} /></Link></div></div><div className="hero-note"><span>01</span><div><b>Delivering value</b><small>Built on capability, safety and trust.</small></div></div></div></section>
  <section className="trust-strip"><div className="container trust-items"><span><ShieldCheck size={19} /> HSE compliant</span><span><Award size={19} /> Quality focused</span><span><Building2 size={19} /> Multi-sector expertise</span><span><Sparkles size={19} /> Client-first delivery</span></div></section>
  <section className="section about-preview"><div className="container split-grid"><div className="image-stack"><img src={images[3].src} alt="Nales Global team at work" /><div className="image-tag"><b>20+</b><span>years of<br />combined expertise</span></div></div><div><SectionIntro eyebrow="Who we are" title="Built for the work that matters." text="Nales Global Services Limited is an indigenous EPC company delivering civil, electrical, mechanical, procurement and contracting solutions across Nigeria’s public and private sectors." /><p className="body-copy">We combine practical engineering know-how with modern project management to keep work moving and outcomes dependable. From first scope to final handover, our focus is simple: do the work properly.</p><Link href="/about" className="text-link strong">More about Nales Global <ArrowRight size={16} /></Link></div></div></section>
  <section className="section soft-bg"><div className="container"><SectionIntro eyebrow="What we do" title="Capability across the project lifecycle." text="One experienced partner for the disciplines, materials and delivery support your project demands."/><div className="service-grid preview-grid">{services.map(s => <ServiceCard item={s} key={s.name} />)}</div><Link href="/services" className="button button-dark centered-button">See all services <ArrowRight size={16} /></Link></div></section>
  <section className="section gallery-preview"><div className="container"><div className="row-heading"><SectionIntro eyebrow="Selected work" title="Proof in the project." text="Real people. Real sites. Real delivery."/><Link href="/gallery" className="text-link">Open project gallery <ArrowRight size={16} /></Link></div><div className="gallery-mosaic"><Link href="/gallery" className="mosaic-large"><img src={images[1].src} alt={images[1].label}/><span>{images[1].label}<ArrowRight size={16}/></span></Link><Link href="/gallery"><img src={images[4].src} alt={images[4].label}/></Link><Link href="/gallery"><img src={images[7].src} alt={images[7].label}/></Link></div></div></section>
  <CTA />
</main></> }

function About() { return <><PageHero eyebrow="About Nales Global" title={<>A dependable partner<br /><em>for complex work.</em></>} text="Indigenous engineering, procurement and construction capability — grounded in the realities of delivering across Nigeria." /><main><section className="section"><div className="container split-grid about-detail"><div><SectionIntro eyebrow="Our story" title="Competence you can build on." text="Nales Global Services Limited is an indigenous EPC company specializing in civil, electrical and mechanical engineering, procurement, technical services and general contracting across Nigeria's public and private sectors."/><p className="body-copy">Our team brings together skilled professionals and trusted technical partners to deliver practical solutions. We understand that a successful project is more than a completed structure — it is safety maintained, quality protected, timelines respected and clients kept informed.</p></div><div className="quote-card"><span className="quote-mark">“</span><p>We deliver value,<br /><em>you grow with us.</em></p><span className="quote-rule" /></div></div></section><section className="section soft-bg"><div className="container"><div className="vision-grid"><div><span className="eyebrow">Our vision</span><h2>To become one of Africa’s most respected and trusted EPC companies.</h2><p>Renowned for world-class infrastructure, innovative engineering solutions and exceptional client value.</p></div><div><span className="eyebrow">Our mission</span><h2>Reliable delivery through people, technology and discipline.</h2><p>We provide engineering, procurement and construction services through competent professionals, modern technology and efficient project management — while maintaining the highest standards of safety, quality and environmental responsibility.</p></div></div></div></section><section className="section"><div className="container"><SectionIntro eyebrow="Why clients choose us" title="The Nales Global standard." text="A focused approach that keeps projects safe, useful and moving forward."/><div className="strength-grid">{["Experienced engineering professionals", "Commitment to quality", "Competitive pricing", "Timely project delivery", "Strict safety standards", "Reliable service delivery"].map((x,i)=><div className="strength" key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div></div></section><CTA /></main></> }

function Services() { const [expanded, setExpanded] = useState<string | null>(null); return <><PageHero eyebrow="Our capabilities" title={<>One team.<br /><em>Many disciplines.</em></>} text="From foundations to facility maintenance, our service lines are designed to work together."/><main><section className="section"><div className="container"><div className="services-list">{services.map((s, i) => {const Icon=s.icon; const is=expanded===s.name; return <article className={`service-row ${is?"expanded":""}`} key={s.name}><div className="service-number">0{i+1}</div><div className="service-row-icon"><Icon size={26}/></div><div className="service-row-main"><h2>{s.name}</h2><p>{s.short}</p>{is && <ul className="expanded-list">{s.bullets.map(b=><li key={b}><Check size={15}/>{b}</li>)}</ul>}</div><button className="expand-button" onClick={()=>setExpanded(is?null:s.name)} aria-label={`Expand ${s.name}`}>{is?<X size={19}/>:<ChevronDown size={19}/>}</button></article>})}</div></div></section><CTA /></main></> }

function Gallery() { const [tab,setTab]=useState<"photos"|"videos">("photos"); const [lightbox,setLightbox]=useState<string|null>(null); const [playing,setPlaying]=useState<string|null>(null); return <><PageHero eyebrow="Project gallery" title={<>Work that speaks<br /><em>for itself.</em></>} text="A selection of project moments from our teams, sites and completed work."/><main><section className="section gallery-section"><div className="container"><div className="filter-row"><div className="tabs"><button className={tab==="photos"?"selected":""} onClick={()=>setTab("photos")}>Photos <span>{images.length}</span></button><button className={tab==="videos"?"selected":""} onClick={()=>setTab("videos")}>Videos <span>{videos.length}</span></button></div><span className="gallery-note">Authentic project documentation</span></div>{tab==="photos"?<div className="photo-grid">{images.slice(1).map((im,i)=><button className={`photo-tile tile-${i%5}`} key={im.src} onClick={()=>setLightbox(im.src)}><img src={im.src} alt={im.label}/><span>{im.label}<ArrowRight size={15}/></span></button>)}</div>:<div className="video-grid">{videos.map(([id,title])=><div className="video-card" key={id}>{playing===id?<iframe src={`https://www.youtube-nocookie.com/embed/${id}?autoplay=1`} title={title} allow="autoplay; encrypted-media; picture-in-picture" allowFullScreen/>:<button onClick={()=>setPlaying(id)}><img src={`https://i.ytimg.com/vi/${id}/hqdefault.jpg`} alt={title}/><span className="play"><Play size={20} fill="currentColor"/></span><b>{title}</b></button>}</div>)}</div>}</div></section></main>{lightbox&&<div className="lightbox" onClick={()=>setLightbox(null)}><button aria-label="Close"><X/></button><img src={lightbox} alt="Expanded project" /></div>}</> }

function Contact() { const [sent,setSent]=useState(false); const handleSubmit=(e: FormEvent<HTMLFormElement>)=>{ e.preventDefault(); const form=new FormData(e.currentTarget); const name=String(form.get("name")||""); const contact=String(form.get("contact")||""); const project=String(form.get("project")||""); const message=String(form.get("message")||""); const whatsappMessage=`Hello Nales Global, my name is ${name}.\n\nProject type: ${project}\nContact: ${contact}\n\n${message}`; window.open(`https://wa.me/2348030615862?text=${encodeURIComponent(whatsappMessage)}`, "_blank", "noopener,noreferrer"); setSent(true); }; return <><PageHero eyebrow="Get in touch" title={<>Let’s build<br /><em>something valuable.</em></>} text="Tell us a little about your project and the right member of our team will get back to you."/><main><section className="section contact-section"><div className="container contact-grid"><div><SectionIntro eyebrow="Contact details" title="A conversation is a good place to start." text="Whether you are planning a new build, maintaining a facility or sourcing technical equipment, we are ready to listen."/><div className="contact-details"><a href="tel:+2348030615862"><span><Phone size={20}/></span><div><small>Call us</small><b>+234 803 061 5862</b><b>+234 701 778 3828</b></div></a><a href="mailto:nalesglobal@yahoo.com"><span><Mail size={20}/></span><div><small>Email</small><b>nalesglobal@yahoo.com</b></div></a><div><span><MapPin size={20}/></span><div><small>Visit us</small><b>10, Ayanbadejo Street</b><b>Ikosi Ketu, Lagos, Nigeria</b></div></div><div className="contact-social"><div><small>Follow our work</small><SocialLinks compact /></div></div></div></div><form className="contact-form" onSubmit={handleSubmit}><span className="eyebrow">Project enquiry</span><h2>How can we help?</h2>{sent?<div className="form-success"><Check size={28}/><h3>WhatsApp is ready.</h3><p>Your enquiry has been prepared in WhatsApp. Review it and tap send to contact our team.</p><button type="button" onClick={()=>setSent(false)} className="text-link">Send another message</button></div>:<><div className="form-row"><label>Name<input name="name" required placeholder="Your name" /></label><label>Email or phone<input name="contact" required placeholder="you@example.com" /></label></div><label>Project type<select name="project" defaultValue="" required><option value="" disabled>Select a service</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label>Message<textarea name="message" required placeholder="Tell us about your project, timeline or requirements..." rows={5}/></label><button className="button button-dark" type="submit">Continue to WhatsApp <Send size={16} /></button></>}</form></div></section></main></> }

export default function App() { return <div className="app"><Header/><Switch><Route path="/" component={Home}/><Route path="/about" component={About}/><Route path="/services" component={Services}/><Route path="/gallery" component={Gallery}/><Route path="/contact" component={Contact}/><Route component={Home}/></Switch><Footer/></div> }
